
package banksystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Alaa
 */
public class firstone extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public firstone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        ageR = new javax.swing.JTextField();
        nameR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordR = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RegisterB = new com.k33ptoo.components.KButton();
        femaleR = new javax.swing.JRadioButton();
        maleR = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addressR = new javax.swing.JComboBox<>();
        nationalidR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        HomeR = new javax.swing.JMenuItem();
        LoginR = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ageR.setBackground(new java.awt.Color(255, 255, 255));
        ageR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageR.setForeground(new java.awt.Color(0, 0, 0));
        ageR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        ageR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageRActionPerformed(evt);
            }
        });
        jPanel1.add(ageR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, 30));

        nameR.setBackground(new java.awt.Color(255, 255, 255));
        nameR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameR.setForeground(new java.awt.Color(0, 0, 0));
        nameR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        nameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRActionPerformed(evt);
            }
        });
        jPanel1.add(nameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 300, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Gender");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 50, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Registeration ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 160, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        passwordR.setBackground(new java.awt.Color(255, 255, 255));
        passwordR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordR.setForeground(new java.awt.Color(0, 0, 0));
        passwordR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        passwordR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRActionPerformed(evt);
            }
        });
        jPanel1.add(passwordR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 300, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("National ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 60, 20));

        RegisterB.setText("Register");
        RegisterB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegisterB.setkEndColor(new java.awt.Color(0, 0, 255));
        RegisterB.setkHoverEndColor(new java.awt.Color(0, 0, 255));
        RegisterB.setkStartColor(new java.awt.Color(255, 0, 255));
        RegisterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 310, -1));

        femaleR.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(femaleR);
        femaleR.setForeground(new java.awt.Color(0, 153, 255));
        femaleR.setText("Female");
        femaleR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRActionPerformed(evt);
            }
        });
        jPanel1.add(femaleR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 90, -1));

        maleR.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(maleR);
        maleR.setForeground(new java.awt.Color(0, 153, 255));
        maleR.setText("Male");
        maleR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRActionPerformed(evt);
            }
        });
        jPanel1.add(maleR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 50, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Age");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 30, 20));

        addressR.setBackground(new java.awt.Color(255, 255, 255));
        addressR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressR.setForeground(new java.awt.Color(0, 153, 204));
        addressR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your Governate", "Cairo", "Alexandria", "Giza", "Qalyubia", "Port Said", "Suez", "Gharbia", "Dakahlia", "Asyut", "Fayoum", "Sharqia", "Ismailia", "Aswan", "Beheira", "Minya", "Damietta", "Luxor", "Qena", "Sohag\t", "Monufia\t", "Beni Suef", "Red Sea", "Kafr el-Sheikh", "North Sinai", "Matruh", "Beheira", "Fayoum", "New Valley", "South Sinai" }));
        addressR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        addressR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressRActionPerformed(evt);
            }
        });
        jPanel1.add(addressR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 300, -1));

        nationalidR.setBackground(new java.awt.Color(255, 255, 255));
        nationalidR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nationalidR.setForeground(new java.awt.Color(0, 0, 0));
        nationalidR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        nationalidR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalidRActionPerformed(evt);
            }
        });
        jPanel1.add(nationalidR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 300, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("E-Mail");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 50, 20));

        emailR.setBackground(new java.awt.Color(255, 255, 255));
        emailR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailR.setForeground(new java.awt.Color(0, 0, 0));
        emailR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        emailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailRActionPerformed(evt);
            }
        });
        jPanel1.add(emailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 300, 30));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 430, 630));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registeration page");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 330, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alaa\\Downloads\\pngaaa.com-468377.png")); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 630, 370));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1370, 780));

        jMenuBar2.setBackground(new java.awt.Color(51, 51, 51));

        jMenu3.setText("Go");

        HomeR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        HomeR.setText("HomePage");
        HomeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeRActionPerformed(evt);
            }
        });
        jMenu3.add(HomeR);

        LoginR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        LoginR.setText("Login Page");
        LoginR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginRActionPerformed(evt);
            }
        });
        jMenu3.add(LoginR);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu3.add(Exit);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageRActionPerformed

    private void nameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRActionPerformed

    private void passwordRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRActionPerformed

    private void femaleRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_femaleRActionPerformed

    private void nationalidRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalidRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalidRActionPerformed

    private void emailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailRActionPerformed

    private void HomeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeRActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeRActionPerformed

    private void RegisterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBActionPerformed
        // TODO add your handling code here:
       //frame
        maleR.setActionCommand("Male");
        femaleR.setActionCommand("Female");
        Integer P ;
        Integer ag ;
        String N ;
        P = Integer.parseInt(passwordR.getText());
        ag = Integer.parseInt(ageR.getText());
        N = nationalidR.getText();
        String selectedValue = addressR.getSelectedItem().toString();
        Account a = new Account();
        //account
         a.setUserName(nameR.getText());
         a.setPassword(P);
         a.setAge(ag);
         a.setNational_ID(N);
         a.setEmail(emailR.getText());
         a.setGender(buttonGroup1.getSelection().getActionCommand());
         a.setAddress(selectedValue);
            
        switch (a.login(a.getUserName(), a.getPassword())) 
       {
            case 1:
                JOptionPane.showMessageDialog(null, "Account already Exist", "Erorr", JOptionPane.ERROR_MESSAGE);
                break;
            
            case -1:
                JOptionPane.showMessageDialog(null, "MySQL Exception!!", "Erorr", JOptionPane.ERROR_MESSAGE);
              break;
            case -2:
                 JOptionPane.showMessageDialog(null, "MySQL Connector Not Found!!", "Erorr", JOptionPane.ERROR_MESSAGE);
                 break;
           default:
                a.registration(a.getUserName(), a.getPassword(), a.getAge(), a.getAddress(), a.getGender(), a.getNational_ID(),a.getEmail(),a.initBalance());
               break;
        }
    }//GEN-LAST:event_RegisterBActionPerformed

    private void maleRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_maleRActionPerformed

    private void addressRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressRActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_addressRActionPerformed

    private void LoginRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginRActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginRActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem HomeR;
    private javax.swing.JMenuItem LoginR;
    private com.k33ptoo.components.KButton RegisterB;
    private javax.swing.JComboBox<String> addressR;
    private javax.swing.JTextField ageR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailR;
    private javax.swing.JRadioButton femaleR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JRadioButton maleR;
    private javax.swing.JTextField nameR;
    private javax.swing.JTextField nationalidR;
    private javax.swing.JPasswordField passwordR;
    // End of variables declaration//GEN-END:variables
}
